apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CLAIRE

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: CLAIRE
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v3
