apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: romaon-two

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: premier
        uses: actions/checkout@v3
      - name: deuxieme
        uses: aws-actions/configure-aws-credentials@v3
      - name: troisieme
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v3
